### PR TITLE
Add support for creating "null" translations

### PR DESCRIPTION
**Pull request by jkobus**
We should be able to tell in the client if the translation beeing created was not specified or if it was an empty string set on purpose.

### CODE REVIEW

**Comment by Nyholm** [comment]
Why would we need this? Isn't this the same as just creating an asset?

Or/ could we flag the translation as untranslated?

**Comment by jkobus** [comment]
see https://github.com/php-translation/loco-adapter/issues/14#issuecomment-316720337

**Comment by Nyholm** [comment]
Do we still need this? We decided to do key=message, right?

**Comment by jkobus** [comment]
We can close it. Not needed anymore.

24.07.2017 11:05 PM "Tobias Nyholm" <notifications@github.com> napisał(a):

**Comment by Nyholm** [comment]
Thank you

**Pull request closed without merging**
